name: deploy

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

deploy:
    uses: "./github/workflows/main.yml"
    runs-on: ubuntu-latest
    env:
        id: ${{ secrets.ORG_ID }}
        authToken: ${{ secrets.AUTH_TOKEN }}
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
          node-version: "16.16.0"
        - run: npm ci
        - run: node ./fetch.js
