name: CI

on:
    push:
        branches:
            - "*"
    workflow_dispatch:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.16.0"
            - run: npm ci
            - run: echo 'hello'

    # lint:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v3
    #     - uses: actions/setup-node@v3
    #       with:
    #         node-version: '16.16.0'
    #     - run: npm ci
    #     - run: npm run lint

    # ts:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v3
    #     - uses: actions/setup-node@v3
    #       with:
    #         node-version: '16.16.0'
    #     - run: npm ci
    #     - run: npm run ts

    # deploy:
    #   needs: [test, lint, ts]
    #   runs-on: ubuntu-latest
    #   env:
    #       id: ${{ secrets.ORG_ID }}
    #       authToken: ${{ secrets.AUTH_TOKEN }}
    #   steps:
    #     - uses: actions/checkout@v3
    #     - uses: actions/setup-node@v3
    #       with:
    #         node-version: '16.16.0'
    #     - run: npm ci
    #     - run: node ./fetch.js
