name: CI

on: [push, workflow_dispatch]

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
          id: ${{ secrets.ORG_ID }}
          authToken: ${{ secrets.AUTH_TOKEN }}
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '16.16.0'
        - run: npm ci
        - run: node ./fetch.js


  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.16.0'
  #     - run: npm ci
  #     - run: npm run test
        
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.16.0'
  #     - run: npm ci
  #     - run: npm run lint
        
  # ts:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.16.0'
  #     - run: npm ci
  #     - run: npm run ts
        